-- Order Details with Customer, Staff, and Item Info
SELECT o.ORD_ID,
       c.CUS_NAME,
       s.STA_NAME,
       o.ORD_TOTALAMOUNT,
       m.ITEM_NAME,
       od.QUANTITY,
       m.ITEM_PRICE,
       (od.QUANTITY * m.ITEM_PRICE) AS ITEM_SUBTOTAL
FROM ORDERS o
JOIN CUSTOMER c ON o.CUS_ID = c.CUS_ID
JOIN STAFF s ON o.STA_ID = s.STA_ID
JOIN ORDERDETAIL od ON o.ORD_ID = od.ORD_ID
JOIN MENUITEM m ON od.ITEM_ID = m.ITEM_ID
ORDER BY o.ORD_ID, m.ITEM_NAME;

-- Customer Spending Summary
SELECT c.CUS_ID,
       c.CUS_NAME,
       SUM(o.ORD_TOTALAMOUNT) AS TOTAL_SPENT,
       COUNT(o.ORD_ID) AS TOTAL_ORDERS
FROM CUSTOMER c
JOIN ORDERS o ON c.CUS_ID = o.CUS_ID
GROUP BY c.CUS_ID, c.CUS_NAME
ORDER BY TOTAL_SPENT DESC;

-- Staff Sales Summary
SELECT s.STA_ID,
       s.STA_NAME,
       COUNT(o.ORD_ID) AS ORDERS_HANDLED,
       NVL(SUM(o.ORD_TOTALAMOUNT), 0) AS TOTAL_SALES
FROM STAFF s
LEFT JOIN ORDERS o ON s.STA_ID = o.STA_ID
GROUP BY s.STA_ID, s.STA_NAME
ORDER BY TOTAL_SALES DESC;

-- Low Stock Items
SELECT ITEM_ID, ITEM_NAME, ITEM_CATEGORY, ITEM_STOCKQTY
FROM MENUITEM
WHERE ITEM_STOCKQTY < 20
ORDER BY ITEM_STOCKQTY ASC;

-- Sales by Item Category
SELECT m.ITEM_CATEGORY,
       SUM(od.QUANTITY) AS TOTAL_QUANTITY_SOLD,
       SUM(od.QUANTITY * m.ITEM_PRICE) AS TOTAL_SALES
FROM MENUITEM m
JOIN ORDERDETAIL od ON m.ITEM_ID = od.ITEM_ID
GROUP BY m.ITEM_CATEGORY
ORDER BY TOTAL_SALES DESC;

-- Top Customers Above Average Spending
SELECT CUS_ID, CUS_NAME
FROM (
    SELECT c.CUS_ID,
           c.CUS_NAME,
           SUM(o.ORD_TOTALAMOUNT) AS TOTAL_SPENT
    FROM CUSTOMER c
    JOIN ORDERS o ON c.CUS_ID = o.CUS_ID
    GROUP BY c.CUS_ID, c.CUS_NAME
) 
WHERE TOTAL_SPENT > (
    SELECT AVG(TOTAL_SPENT) 
    FROM (
        SELECT SUM(o.ORD_TOTALAMOUNT) AS TOTAL_SPENT
        FROM CUSTOMER c
        JOIN ORDERS o ON c.CUS_ID = o.CUS_ID
        GROUP BY c.CUS_ID
    )
);

-- Details of a Specific Order
SELECT o.ORD_ID, m.ITEM_NAME, od.QUANTITY, m.ITEM_PRICE, (od.QUANTITY*m.ITEM_PRICE) AS SUBTOTAL
FROM ORDERDETAIL od
JOIN MENUITEM m ON od.ITEM_ID = m.ITEM_ID
JOIN ORDERS o ON od.ORD_ID = o.ORD_ID
WHERE o.ORD_ID = 'O1006';

-- Supplier Inventory Summary
SELECT sup.SUP_ID,
       sup.SUP_NAME,
       COUNT(m.ITEM_ID) AS NUM_ITEMS,
       SUM(m.ITEM_STOCKQTY) AS TOTAL_STOCK
FROM SUPPLIER sup
LEFT JOIN MENUITEM m ON sup.SUP_ID = m.SUP_ID
GROUP BY sup.SUP_ID, sup.SUP_NAME
ORDER BY TOTAL_STOCK DESC;

-- 1. Customer Spending Analysis Above Average
SELECT 
    C.CUS_ID,
    C.CUS_NAME,
    COUNT(DISTINCT O.ORD_ID) AS TOTAL_ORDERS,
    SUM(OD.QUANTITY * M.ITEM_PRICE) AS TOTAL_SPENT,
    RANK() OVER (ORDER BY SUM(OD.QUANTITY * M.ITEM_PRICE) DESC) AS SPENDING_RANK
FROM CUSTOMER C
JOIN ORDERS O ON C.CUS_ID = O.CUS_ID
JOIN ORDERDETAIL OD ON O.ORD_ID = OD.ORD_ID
JOIN MENUITEM M ON OD.ITEM_ID = M.ITEM_ID
GROUP BY C.CUS_ID, C.CUS_NAME
HAVING SUM(OD.QUANTITY * M.ITEM_PRICE) > (
    SELECT AVG(TOTAL_SPENT) FROM (
        SELECT SUM(OD.QUANTITY * M.ITEM_PRICE) AS TOTAL_SPENT
        FROM CUSTOMER C
        JOIN ORDERS O ON C.CUS_ID = O.CUS_ID
        JOIN ORDERDETAIL OD ON O.ORD_ID = OD.ORD_ID
        JOIN MENUITEM M ON OD.ITEM_ID = M.ITEM_ID
        GROUP BY C.CUS_ID
    )
)
ORDER BY TOTAL_SPENT DESC;

-- 2. Staff Sales Performance with Top-Selling Item
WITH EMP_SALES AS (
    SELECT 
        S.STA_ID,
        S.STA_NAME,
        COUNT(DISTINCT O.ORD_ID) AS TOTAL_ORDERS,
        SUM(OD.QUANTITY * M.ITEM_PRICE) AS TOTAL_SALES
    FROM STAFF S
    JOIN ORDERS O ON S.STA_ID = O.STA_ID
    JOIN ORDERDETAIL OD ON O.ORD_ID = OD.ORD_ID
    JOIN MENUITEM M ON OD.ITEM_ID = M.ITEM_ID
    GROUP BY S.STA_ID, S.STA_NAME
),
EMP_TOP_ITEM AS (
    SELECT
        O.STA_ID,
        OD.ITEM_ID,
        M.ITEM_NAME,
        SUM(OD.QUANTITY) AS TOTAL_SOLD,
        RANK() OVER (PARTITION BY O.STA_ID ORDER BY SUM(OD.QUANTITY) DESC) AS ITEM_RANK
    FROM ORDERS O
    JOIN ORDERDETAIL OD ON O.ORD_ID = OD.ORD_ID
    JOIN MENUITEM M ON OD.ITEM_ID = M.ITEM_ID
    GROUP BY O.STA_ID, OD.ITEM_ID, M.ITEM_NAME
)
SELECT 
    E.STA_ID,
    E.STA_NAME,
    E.TOTAL_ORDERS,
    E.TOTAL_SALES,
    T.ITEM_NAME AS TOP_ITEM,
    T.TOTAL_SOLD
FROM EMP_SALES E
LEFT JOIN EMP_TOP_ITEM T ON E.STA_ID = T.STA_ID AND T.ITEM_RANK = 1
ORDER BY E.TOTAL_SALES DESC;

-- 3. Menu Item Sales and Inventory Status Analysis
SELECT 
    M.ITEM_ID,
    M.ITEM_NAME,
    M.ITEM_CATEGORY,
    NVL(SUM(OD.QUANTITY), 0) AS TOTAL_SOLD,
    NVL(SUM(OD.QUANTITY * M.ITEM_PRICE), 0) AS TOTAL_REVENUE,
    M.ITEM_STOCKQTY,
    CASE 
        WHEN M.ITEM_STOCKQTY < 10 THEN 'LOW STOCK'
        ELSE 'STOCK OK'
    END AS STOCK_STATUS
FROM MENUITEM M
LEFT JOIN ORDERDETAIL OD ON M.ITEM_ID = OD.ITEM_ID
GROUP BY M.ITEM_ID, M.ITEM_NAME, M.ITEM_CATEGORY, M.ITEM_STOCKQTY
ORDER BY TOTAL_REVENUE DESC;

-- 4. Daily and Cumulative Sales Trend Analysis
SELECT
    TO_CHAR(O.ORD_DATE,'YYYY-MM-DD') AS SALE_DATE,
    SUM(OD.QUANTITY * M.ITEM_PRICE) AS DAILY_SALES,
    SUM(SUM(OD.QUANTITY * M.ITEM_PRICE)) OVER (ORDER BY TO_CHAR(O.ORD_DATE,'YYYY-MM-DD')) AS CUMULATIVE_SALES
FROM ORDERS O
JOIN ORDERDETAIL OD ON O.ORD_ID = OD.ORD_ID
JOIN MENUITEM M ON OD.ITEM_ID = M.ITEM_ID
GROUP BY TO_CHAR(O.ORD_DATE,'YYYY-MM-DD')
ORDER BY SALE_DATE;

-- Supplier Inventory Value Summary
SELECT 
    S.SUP_ID,
    S.SUP_NAME,
    COUNT(M.ITEM_ID) AS TOTAL_ITEMS,
    SUM(M.ITEM_STOCKQTY) AS TOTAL_STOCK,
    SUM(M.ITEM_STOCKQTY * M.ITEM_PRICE) AS TOTAL_VALUE
FROM SUPPLIER S
LEFT JOIN MENUITEM M ON S.SUP_ID = M.SUP_ID
GROUP BY S.SUP_ID, S.SUP_NAME
ORDER BY TOTAL_VALUE DESC;





