-- 1) CUSTOMER
CREATE TABLE CUSTOMER (
  CUS_ID     CHAR(10) PRIMARY KEY,
  CUS_NAME   VARCHAR2(20) NOT NULL,
  CUS_PHONE  VARCHAR2(13)
);

-- 2) STAFF
CREATE TABLE STAFF (
  STA_ID      CHAR(10) PRIMARY KEY,
  STA_NAME    VARCHAR2(20) NOT NULL,
  STA_ROLE    VARCHAR2(30) NOT NULL,
  STA_CONTACT VARCHAR2(13),
  STA_SHIFT   VARCHAR2(30),
  CONSTRAINT CK_STAFF_ROLE
    CHECK (STA_ROLE IN ('Manager','Kitchen Staff','Main Chef','Cashier','Waiter','Waitress','Supervisor'))
);

-- 3) SUPPLIER
CREATE TABLE SUPPLIER (
  SUP_ID      CHAR(10) PRIMARY KEY,
  SUP_NAME    VARCHAR2(20) NOT NULL,
  SUP_CONTACT VARCHAR2(13)
);

-- 4) MENUITEM
CREATE TABLE MENUITEM (
  ITEM_ID        CHAR(10) PRIMARY KEY,
  ITEM_NAME      VARCHAR2(30) NOT NULL,
  ITEM_CATEGORY  VARCHAR2(30) NOT NULL,
  ITEM_PRICE     NUMBER(8,2) NOT NULL,
  ITEM_STOCKQTY  NUMBER(8) NOT NULL,
  SUP_ID         CHAR(10) NOT NULL,
  CONSTRAINT CK_ITEM_PRICE CHECK (ITEM_PRICE >= 0),
  CONSTRAINT CK_ITEM_STOCK CHECK (ITEM_STOCKQTY >= 0),
  CONSTRAINT FK_MENU_SUPPLIER FOREIGN KEY (SUP_ID) REFERENCES SUPPLIER(SUP_ID)
);

-- 5) ORDERS  
CREATE TABLE ORDERS (
  ORD_ID          CHAR(10) PRIMARY KEY,
  ORD_DATE        DATE NOT NULL,
  ORD_TOTALAMOUNT NUMBER(10,2) DEFAULT 0 NOT NULL,
  CUS_ID          CHAR(10) NOT NULL,
  STA_ID          CHAR(10) NOT NULL,
  CONSTRAINT CK_ORDER_TOTAL CHECK (ORD_TOTALAMOUNT >= 0),
  CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
  CONSTRAINT FK_ORDER_STAFF FOREIGN KEY (STA_ID) REFERENCES STAFF(STA_ID)
);

-- 6) ORDERDETAIL
CREATE TABLE ORDERDETAIL (
  ORD_ID       CHAR(10) NOT NULL,
  ITEM_ID      CHAR(10) NOT NULL,
  QUANTITY     NUMBER(6) NOT NULL,
  CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORD_ID, ITEM_ID),
  CONSTRAINT CK_OD_QTY CHECK (QUANTITY > 0),
  CONSTRAINT FK_OD_ORDER FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID),
  CONSTRAINT FK_OD_ITEM FOREIGN KEY (ITEM_ID) REFERENCES MENUITEM(ITEM_ID)
);

ALTER TABLE MENUITEM
MODIFY ITEM_NAME VARCHAR2(50);

DROP TABLE ORDERDETAIL CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE MENUITEM CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;

DESC MENUITEM;
SELECT 
    COLUMN_NAME AS "Column",
    CASE WHEN NULLABLE = 'N' THEN 'NOT NULL' ELSE '' END AS "Nullable",
    DATA_TYPE || 
    CASE 
        WHEN DATA_TYPE IN ('CHAR', 'VARCHAR2') THEN '(' || DATA_LENGTH || ')'
        WHEN DATA_TYPE = 'NUMBER' AND DATA_PRECISION IS NOT NULL AND DATA_SCALE IS NOT NULL 
            THEN '(' || DATA_PRECISION || ',' || DATA_SCALE || ')'
        WHEN DATA_TYPE = 'NUMBER' AND DATA_PRECISION IS NOT NULL AND DATA_SCALE = 0 
            THEN '(' || DATA_PRECISION || ')'
        ELSE ''
    END AS "Data Type",
    COLUMN_ID AS "Order"
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MENUITEM'
ORDER BY COLUMN_ID;

COMMIT;


